// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orm.Context;

#nullable disable

namespace Orm.Migrations
{
    [DbContext(typeof(PetShopContext))]
    [Migration("20230207191518_Fourth")]
    partial class Fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.CustomerF", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CustomerSurname")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TIN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("TransactionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("int");

                    b.Property<double>("SalaryPerMonth")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<Guid>("TransactionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Model.MonthlyLedger", b =>
                {
                    b.Property<Guid>("MonthlyLedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Expenses")
                        .HasPrecision(15)
                        .HasColumnType("float(15)");

                    b.Property<double>("Income")
                        .HasPrecision(20)
                        .HasColumnType("float(20)");

                    b.Property<int>("Month")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<double>("TotalSold")
                        .HasPrecision(20)
                        .HasColumnType("float(20)");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("MonthlyLedID");

                    b.ToTable("MonthlyLedger", (string)null);
                });

            modelBuilder.Entity("Model.Pet", b =>
                {
                    b.Property<Guid>("PetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int>("PetStatus")
                        .HasColumnType("int");

                    b.Property<int>("PetType")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<Guid>("TransactionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PetID");

                    b.ToTable("Pet", (string)null);
                });

            modelBuilder.Entity("Model.PetFood", b =>
                {
                    b.Property<Guid>("PetFoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnimalType")
                        .HasColumnType("int");

                    b.Property<double>("PetFoodCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("PetFoodPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<Guid>("SpecialOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionLineID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PetFoodID");

                    b.ToTable("PetFood", (string)null);
                });

            modelBuilder.Entity("Model.PetReport", b =>
                {
                    b.Property<Guid>("PetReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnimalType")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<double>("TotalSold")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PetReportID");

                    b.ToTable("PetReports");
                });

            modelBuilder.Entity("Model.SpecialOffer", b =>
                {
                    b.Property<Guid>("SpecialOfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetFoodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PetFoodPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("TransactionLineID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpecialOfferID");

                    b.HasIndex("PetFoodID")
                        .IsUnique();

                    b.ToTable("SpecialOffer", (string)null);
                });

            modelBuilder.Entity("Model.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerID")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeID")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PetFoodPrice")
                        .HasPrecision(10, 5)
                        .HasColumnType("float(10)");

                    b.Property<int>("PetFoodQty")
                        .HasColumnType("int");

                    b.Property<double>("PetPrice")
                        .HasPrecision(10)
                        .HasColumnType("float(10)");

                    b.Property<double>("TotalPrice")
                        .HasPrecision(10, 5)
                        .HasColumnType("float(10)");

                    b.Property<DateTime>("TransactionDate")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionLineID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Model.TransactionLine", b =>
                {
                    b.Property<Guid>("TransactionLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("PetFoodCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<Guid>("PetFoodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PetFoodPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int>("PetFoodQty")
                        .HasColumnType("int");

                    b.Property<Guid>("PetID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PetPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("PriceDiscount")
                        .HasColumnType("float");

                    b.Property<Guid>("SpecialOfferID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionLineID");

                    b.HasIndex("PetFoodID")
                        .IsUnique();

                    b.HasIndex("PetID")
                        .IsUnique();

                    b.HasIndex("SpecialOfferID")
                        .IsUnique();

                    b.HasIndex("TransactionID");

                    b.ToTable("TransactionLine", (string)null);
                });

            modelBuilder.Entity("Model.SpecialOffer", b =>
                {
                    b.HasOne("Model.PetFood", "PetFood")
                        .WithOne("SpecialOffer")
                        .HasForeignKey("Model.SpecialOffer", "PetFoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetFood");
                });

            modelBuilder.Entity("Model.Transaction", b =>
                {
                    b.HasOne("Model.CustomerF", "Customer")
                        .WithOne("Transaction")
                        .HasForeignKey("Model.Transaction", "CustomerID")
                        .IsRequired();

                    b.HasOne("Model.Employee", "Employee")
                        .WithOne("Transaction")
                        .HasForeignKey("Model.Transaction", "EmployeeID")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Model.TransactionLine", b =>
                {
                    b.HasOne("Model.PetFood", "PetFood")
                        .WithOne("TransactionLine")
                        .HasForeignKey("Model.TransactionLine", "PetFoodID")
                        .IsRequired();

                    b.HasOne("Model.Pet", "Pet")
                        .WithOne("TransactionLine")
                        .HasForeignKey("Model.TransactionLine", "PetID")
                        .IsRequired();

                    b.HasOne("Model.SpecialOffer", "SpecialOffer")
                        .WithOne("TransactionLine")
                        .HasForeignKey("Model.TransactionLine", "SpecialOfferID")
                        .IsRequired();

                    b.HasOne("Model.Transaction", "Transastion")
                        .WithMany("TransactionLines")
                        .HasForeignKey("TransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("PetFood");

                    b.Navigation("SpecialOffer");

                    b.Navigation("Transastion");
                });

            modelBuilder.Entity("Model.CustomerF", b =>
                {
                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Pet", b =>
                {
                    b.Navigation("TransactionLine")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PetFood", b =>
                {
                    b.Navigation("SpecialOffer")
                        .IsRequired();

                    b.Navigation("TransactionLine")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.SpecialOffer", b =>
                {
                    b.Navigation("TransactionLine")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Transaction", b =>
                {
                    b.Navigation("TransactionLines");
                });
#pragma warning restore 612, 618
        }
    }
}
